"""Initial Psychogram MVP schema (static snapshot).

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-15 23:20:45.056370
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("org_type", sa.String(length=40), nullable=False),
        sa.Column("region", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=500), nullable=False),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_events",
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("research_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("safe_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_research_id"),
        "audit_events",
        ["research_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("can_view_pii", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role in ('owner','admin','researcher','operator','auditor')",
            name="ck_membership_role",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_membership_tenant_user"),
    )
    op.create_index(
        op.f("ix_memberships_tenant_id"), "memberships", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False
    )
    op.create_table(
        "methodologies",
        sa.Column("methodology_code", sa.String(length=64), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("purpose_summary", sa.Text(), nullable=False),
        sa.Column("owner_name", sa.String(length=300), nullable=False),
        sa.Column("source_reference", sa.String(length=1000), nullable=False),
        sa.Column("catalog_status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("methodology_code"),
    )
    op.create_table(
        "retention_policies",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", name="uq_retention_tenant_code"),
    )
    op.create_table(
        "methodology_versions",
        sa.Column("methodology_id", sa.String(length=36), nullable=False),
        sa.Column("version_code", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=40), nullable=False),
        sa.Column("default_locale", sa.String(length=32), nullable=False),
        sa.Column("supported_locales", sa.JSON(), nullable=False),
        sa.Column("target_population", sa.JSON(), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=20), nullable=False),
        sa.Column("content_hash", sa.String(length=72), nullable=True),
        sa.Column("engine_contract_version", sa.String(length=32), nullable=False),
        sa.Column("disclaimer_i18n", sa.JSON(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("template_id", sa.String(length=80), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("supersedes_version_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "lifecycle_status in "
            "('draft','in_review','published','deprecated','withdrawn')",
            name="ck_methodology_version_status",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["methodology_id"],
            ["methodologies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_version_id"],
            ["methodology_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "methodology_id", "version_code", name="uq_methodology_version"
        ),
    )
    op.create_table(
        "column_mappings",
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("template_id", sa.String(length=80), nullable=False),
        sa.Column("source_headers_hash", sa.String(length=72), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "items",
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("item_code", sa.String(length=64), nullable=False),
        sa.Column("item_type", sa.String(length=24), nullable=False),
        sa.Column("prompt_i18n", sa.JSON(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("value_constraints", sa.JSON(), nullable=False),
        sa.Column("missing_policy", sa.JSON(), nullable=False),
        sa.Column("score_mapping", sa.JSON(), nullable=False),
        sa.Column("reverse_scoring", sa.JSON(), nullable=False),
        sa.Column("item_transform_expr", sa.JSON(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("methodology_version_id", "item_code", name="uq_item_code"),
    )
    op.create_table(
        "licence_revisions",
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("licence_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("copyright_status", sa.String(length=32), nullable=False),
        sa.Column("rights_holder", sa.String(length=300), nullable=False),
        sa.Column("evidence_reference", sa.String(length=1000), nullable=False),
        sa.Column("allowed_use_types", sa.JSON(), nullable=False),
        sa.Column("allowed_org_types", sa.JSON(), nullable=False),
        sa.Column("allowed_regions", sa.JSON(), nullable=False),
        sa.Column("content_disclosure_level", sa.String(length=24), nullable=False),
        sa.Column("allow_item_display", sa.Boolean(), nullable=False),
        sa.Column("allow_item_export", sa.Boolean(), nullable=False),
        sa.Column("allow_trace_item_values", sa.Boolean(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("required_disclaimer_i18n", sa.JSON(), nullable=False),
        sa.Column("restrictions_i18n", sa.JSON(), nullable=False),
        sa.Column("verified_by", sa.String(length=36), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "methodology_version_id", "licence_revision", name="uq_licence_revision"
        ),
    )
    op.create_table(
        "researches",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("pii_mode", sa.String(length=24), nullable=False),
        sa.Column("consent_reference", sa.String(length=1000), nullable=False),
        sa.Column("consent_version", sa.String(length=64), nullable=False),
        sa.Column("retention_policy_id", sa.String(length=36), nullable=False),
        sa.Column("responsible_user_id", sa.String(length=36), nullable=False),
        sa.Column("use_type", sa.String(length=24), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retention_policy_id"],
            ["retention_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_research_tenant_id"),
    )
    op.create_index(
        op.f("ix_researches_tenant_id"), "researches", ["tenant_id"], unique=False
    )
    op.create_table(
        "scales",
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("scale_code", sa.String(length=64), nullable=False),
        sa.Column("scale_kind", sa.String(length=20), nullable=False),
        sa.Column("label_i18n", sa.JSON(), nullable=False),
        sa.Column("unit_code", sa.String(length=64), nullable=False),
        sa.Column("theoretical_min", sa.String(length=40), nullable=False),
        sa.Column("theoretical_max", sa.String(length=40), nullable=False),
        sa.Column("display_decimals", sa.Integer(), nullable=False),
        sa.Column("aggregation", sa.JSON(), nullable=False),
        sa.Column("transform_expr", sa.JSON(), nullable=True),
        sa.Column("validity_rules", sa.JSON(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "methodology_version_id", "scale_code", name="uq_scale_code"
        ),
    )
    op.create_table(
        "import_jobs",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("file_hash", sa.String(length=72), nullable=False),
        sa.Column("preview_hash", sa.String(length=72), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("staged_rows", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_jobs_tenant_id"), "import_jobs", ["tenant_id"], unique=False
    )
    op.create_table(
        "interpretation_rules",
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("scale_id", sa.String(length=36), nullable=False),
        sa.Column("rule_code", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("when_expr", sa.JSON(), nullable=False),
        sa.Column("interpretation_code", sa.String(length=64), nullable=False),
        sa.Column("title_i18n", sa.JSON(), nullable=False),
        sa.Column("text_i18n", sa.JSON(), nullable=False),
        sa.Column("disclaimer_i18n", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scale_id", "rule_code", name="uq_interpretation_rule"),
    )
    op.create_table(
        "legal_holds",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "norm_sets",
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("scale_id", sa.String(length=36), nullable=False),
        sa.Column("norm_code", sa.String(length=64), nullable=False),
        sa.Column("label_i18n", sa.JSON(), nullable=False),
        sa.Column("norm_kind", sa.String(length=24), nullable=False),
        sa.Column("population_descriptor", sa.JSON(), nullable=False),
        sa.Column("selection_constraints", sa.JSON(), nullable=False),
        sa.Column("source_reference", sa.String(length=1000), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("lookup_mode", sa.String(length=16), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scale_id", "norm_code", name="uq_scale_norm"),
    )
    op.create_table(
        "participants",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("external_code", sa.String(length=120), nullable=False),
        sa.Column("processing_status", sa.String(length=24), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "research_id", "external_code", name="uq_participant_code"
        ),
        sa.UniqueConstraint(
            "tenant_id", "research_id", "id", name="uq_participant_scope"
        ),
    )
    op.create_index(
        op.f("ix_participants_research_id"),
        "participants",
        ["research_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_participants_tenant_id"), "participants", ["tenant_id"], unique=False
    )
    op.create_table(
        "research_methodology_pins",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("methodology_content_hash", sa.String(length=72), nullable=False),
        sa.Column("norm_selection", sa.JSON(), nullable=False),
        sa.Column("pinned_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pinned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "research_id", name="uq_research_pin"),
    )
    op.create_table(
        "response_options",
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("option_code", sa.String(length=64), nullable=False),
        sa.Column("label_i18n", sa.JSON(), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=False),
        sa.Column("score_value", sa.String(length=40), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("item_id", "option_code", name="uq_item_option"),
    )
    op.create_table(
        "scale_item_links",
        sa.Column("scale_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("weight", sa.String(length=40), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scale_id", "item_id", name="uq_scale_item"),
    )
    op.create_table(
        "consent_records",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=1000), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("obtained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by", sa.String(length=36), nullable=False),
        sa.Column("basis", sa.Text(), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_records_tenant_id"),
        "consent_records",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "import_issues",
        sa.Column("import_job_id", sa.String(length=36), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("column_name", sa.String(length=160), nullable=True),
        sa.Column("item_code", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.Column("safe_params", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "norm_bands",
        sa.Column("norm_set_id", sa.String(length=36), nullable=False),
        sa.Column("band_code", sa.String(length=64), nullable=False),
        sa.Column("lower_bound", sa.String(length=40), nullable=True),
        sa.Column("lower_inclusive", sa.Boolean(), nullable=False),
        sa.Column("upper_bound", sa.String(length=40), nullable=True),
        sa.Column("upper_inclusive", sa.Boolean(), nullable=False),
        sa.Column("normalized_value", sa.String(length=40), nullable=True),
        sa.Column("label_i18n", sa.JSON(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["norm_set_id"],
            ["norm_sets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("norm_set_id", "band_code", name="uq_norm_band"),
    )
    op.create_table(
        "participant_pii",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=False),
        sa.Column("encrypted_payload", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "participant_id", name="uq_participant_pii"),
    )
    op.create_table(
        "responses",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_key", sa.String(length=64), nullable=False),
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("current_revision_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "research_id", "id", name="uq_response_scope"),
        sa.UniqueConstraint(
            "tenant_id",
            "research_id",
            "participant_id",
            "attempt_key",
            name="uq_response_attempt",
        ),
    )
    op.create_index(
        op.f("ix_responses_research_id"), "responses", ["research_id"], unique=False
    )
    op.create_index(
        op.f("ix_responses_tenant_id"), "responses", ["tenant_id"], unique=False
    )
    op.create_table(
        "import_rows",
        sa.Column("import_job_id", sa.String(length=36), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=True),
        sa.Column("response_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["responses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "response_revisions",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("response_id", sa.String(length=36), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("answer_payload_hash", sa.String(length=72), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("validation_summary", sa.JSON(), nullable=False),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=36), nullable=True),
        sa.Column("correction_reason", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["responses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "response_id", "revision_number", name="uq_response_revision_number"
        ),
    )
    op.create_index(
        op.f("ix_response_revisions_tenant_id"),
        "response_revisions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "calculation_runs",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("response_revision_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("computation_key", sa.String(length=72), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("rule_interpreter_version", sa.String(length=32), nullable=False),
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("methodology_content_hash", sa.String(length=72), nullable=False),
        sa.Column("licence_id", sa.String(length=36), nullable=False),
        sa.Column("licence_revision", sa.Integer(), nullable=False),
        sa.Column("initiated_by", sa.String(length=36), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("diagnostic_ref", sa.String(length=64), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["initiated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["licence_id"],
            ["licence_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_revision_id"],
            ["response_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "computation_key", name="uq_calculation_computation"
        ),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_calculation_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_calculation_runs_tenant_id"),
        "calculation_runs",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "response_validation_issues",
        sa.Column("response_revision_id", sa.String(length=36), nullable=False),
        sa.Column("item_code", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.Column("safe_params", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["response_revision_id"],
            ["response_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "results",
        sa.Column("calculation_run_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("research_id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=False),
        sa.Column("response_id", sa.String(length=36), nullable=False),
        sa.Column("response_revision_id", sa.String(length=36), nullable=False),
        sa.Column("methodology_version_id", sa.String(length=36), nullable=False),
        sa.Column("methodology_content_hash", sa.String(length=72), nullable=False),
        sa.Column("status", sa.String(length=48), nullable=False),
        sa.Column("disclaimer_i18n_snapshot", sa.JSON(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculated_by", sa.String(length=36), nullable=False),
        sa.Column("result_hash", sa.String(length=72), nullable=False),
        sa.Column("retention_classification", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["calculation_run_id"],
            ["calculation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["researches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["responses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_revision_id"],
            ["response_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calculation_run_id"),
    )
    op.create_index(
        op.f("ix_results_tenant_id"), "results", ["tenant_id"], unique=False
    )
    op.create_table(
        "explainability_traces",
        sa.Column("calculation_run_id", sa.String(length=36), nullable=False),
        sa.Column("result_id", sa.String(length=36), nullable=False),
        sa.Column("trace_schema_version", sa.String(length=32), nullable=False),
        sa.Column("disclosure_level_applied", sa.String(length=24), nullable=False),
        sa.Column("methodology_content_hash", sa.String(length=72), nullable=False),
        sa.Column("response_revision_hash", sa.String(length=72), nullable=False),
        sa.Column("trace_hash", sa.String(length=72), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_run_id"],
            ["calculation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calculation_run_id"),
        sa.UniqueConstraint("result_id"),
    )
    op.create_table(
        "scale_results",
        sa.Column("result_id", sa.String(length=36), nullable=False),
        sa.Column("scale_id", sa.String(length=36), nullable=True),
        sa.Column("scale_code", sa.String(length=64), nullable=False),
        sa.Column("validity_status", sa.String(length=40), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("answered_count", sa.Integer(), nullable=False),
        sa.Column("missing_count", sa.Integer(), nullable=False),
        sa.Column("aggregate_score_unrounded", sa.String(length=80), nullable=True),
        sa.Column("score_unrounded", sa.String(length=80), nullable=True),
        sa.Column("score_display", sa.String(length=80), nullable=True),
        sa.Column("unit_code", sa.String(length=64), nullable=False),
        sa.Column("norm_set_id", sa.String(length=36), nullable=True),
        sa.Column("norm_band_code", sa.String(length=64), nullable=True),
        sa.Column("normalized_value", sa.String(length=80), nullable=True),
        sa.Column("interpretation_rule_id", sa.String(length=36), nullable=True),
        sa.Column("interpretation_code", sa.String(length=64), nullable=True),
        sa.Column("interpretation_snapshot_i18n", sa.JSON(), nullable=True),
        sa.Column("disclosure_level_applied", sa.String(length=24), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["interpretation_rule_id"],
            ["interpretation_rules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["norm_set_id"],
            ["norm_sets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["result_id"],
            ["results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("result_id", "scale_code", name="uq_result_scale"),
    )
    op.create_table(
        "trace_steps",
        sa.Column("trace_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("step_code", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("entity_ref", sa.JSON(), nullable=True),
        sa.Column("rule_ref", sa.String(length=200), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("message_key", sa.String(length=160), nullable=False),
        sa.Column("redactions", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["explainability_traces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trace_id", "sequence", name="uq_trace_sequence"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trace_steps")
    op.drop_table("scale_results")
    op.drop_table("explainability_traces")
    op.drop_index(op.f("ix_results_tenant_id"), table_name="results")
    op.drop_table("results")
    op.drop_table("response_validation_issues")
    op.drop_index(op.f("ix_calculation_runs_tenant_id"), table_name="calculation_runs")
    op.drop_table("calculation_runs")
    op.drop_index(
        op.f("ix_response_revisions_tenant_id"), table_name="response_revisions"
    )
    op.drop_table("response_revisions")
    op.drop_table("import_rows")
    op.drop_index(op.f("ix_responses_tenant_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_research_id"), table_name="responses")
    op.drop_table("responses")
    op.drop_table("participant_pii")
    op.drop_table("norm_bands")
    op.drop_table("import_issues")
    op.drop_index(op.f("ix_consent_records_tenant_id"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_table("scale_item_links")
    op.drop_table("response_options")
    op.drop_table("research_methodology_pins")
    op.drop_index(op.f("ix_participants_tenant_id"), table_name="participants")
    op.drop_index(op.f("ix_participants_research_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_table("norm_sets")
    op.drop_table("legal_holds")
    op.drop_table("interpretation_rules")
    op.drop_index(op.f("ix_import_jobs_tenant_id"), table_name="import_jobs")
    op.drop_table("import_jobs")
    op.drop_table("scales")
    op.drop_index(op.f("ix_researches_tenant_id"), table_name="researches")
    op.drop_table("researches")
    op.drop_table("licence_revisions")
    op.drop_table("items")
    op.drop_table("column_mappings")
    op.drop_table("methodology_versions")
    op.drop_table("retention_policies")
    op.drop_table("methodologies")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_tenant_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_research_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("organizations")
    # ### end Alembic commands ###
