import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Button, Empty, ErrorNotice, Field, Loading, Notice, Page, Status } from '../components/UI'
import { useApi, useAuth } from '../context/AuthContext'
import { safeMessage } from '../lib/api'
import type { Retention } from '../types'
import { tenantKey } from '../lib/queryKeys'

interface Member {user_id:string;email:string;full_name:string;role:string;can_view_pii:boolean;active:boolean}
interface Methodology {id:string;methodology_code:string;canonical_name:string;catalog_status:string}

export function TeamPage(){
 const call=useApi();const qc=useQueryClient();const {membership}=useAuth();const key=tenantKey(membership?.organization_id,'members');const [open,setOpen]=useState(false);const [error,setError]=useState('');const query=useQuery({queryKey:key,queryFn:()=>call<Member[]>('/api/v1/organizations/current/members')})
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{await call('/api/v1/organizations/current/members',{method:'POST',bodyJson:{email:f.get('email'),full_name:f.get('full_name'),password:f.get('password'),role:f.get('role'),can_view_pii:f.get('can_view_pii')==='on'}});await qc.invalidateQueries({queryKey:key});setOpen(false)}catch(err){setError(safeMessage(err))}}
 return <Page eyebrow="Ruxsatlar daftari" title="Jamoa" actions={<Button onClick={()=>setOpen(v=>!v)}>A’zo qo‘shish</Button>}>{error&&<Notice tone="danger" title="A’zo qo‘shilmadi">{error}</Notice>}{open&&<form className="inline-form" onSubmit={add}><div className="form-grid"><Field label="To‘liq ism"><input name="full_name" required/></Field><Field label="Email"><input name="email" type="email" required/></Field><Field label="Vaqtinchalik parol"><input name="password" type="password" minLength={12} required/></Field><Field label="Rol"><select name="role"><option value="researcher">Researcher</option><option value="operator">Operator</option><option value="auditor">Auditor</option><option value="admin">Admin</option></select></Field></div><label className="choice privacy-choice"><input name="can_view_pii" type="checkbox"/> PII ko‘rish huquqi <small>Bu rolga qo‘shimcha, audit qilinadigan ruxsat.</small></label><Button type="submit">A’zoni yaratish</Button></form>}{query.isLoading?<Loading/>:query.error?<ErrorNotice error={query.error}/>:<div className="data-table-wrap"><table><thead><tr><th>Foydalanuvchi</th><th>Rol</th><th>PII</th><th>Holat</th></tr></thead><tbody>{query.data?.map(m=><tr key={m.user_id}><td><strong>{m.full_name}</strong><small>{m.email}</small></td><td>{m.role}</td><td>{m.can_view_pii?'Ruxsat bor':'Ruxsat yo‘q'}</td><td><Status value={m.active?'active':'inactive'}/></td></tr>)}</tbody></table></div>}<Notice title="MVP chegarasi">Member update, revoke va PII permission update endpointlari yo‘q; phantom boshqaruv ko‘rsatilmaydi.</Notice></Page>
}

export function RetentionPage(){
 const call=useApi();const qc=useQueryClient();const {membership}=useAuth();const key=tenantKey(membership?.organization_id,'retention');const [error,setError]=useState('');const query=useQuery({queryKey:key,queryFn:()=>call<Retention[]>('/api/v1/retention-policies')});async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await call('/api/v1/retention-policies',{method:'POST',bodyJson:{code:f.get('code'),retention_days:Number(f.get('retention_days'))}});await qc.invalidateQueries({queryKey:key});e.currentTarget.reset()}catch(err){setError(safeMessage(err))}}
 return <Page eyebrow="Ma’lumot hayot sikli" title="Retention siyosatlari"><div className="workbench-grid"><section>{query.isLoading?<Loading/>:query.error?<ErrorNotice error={query.error}/>:!query.data?.length?<Empty title="Siyosat hali yo‘q" icon="archive">Research ochishdan oldin muddat yarating.</Empty>:<div className="ledger">{query.data.map(p=><div className="ledger-row" key={p.id}><strong>{p.code}</strong><span>{p.retention_days} kun</span><Status value={p.active?'active':'inactive'}/><code>{p.id.slice(0,8)}…</code></div>)}</div>}</section><aside className="inspector"><h2>Yangi siyosat</h2>{error&&<Notice tone="danger" title="Saqlanmadi">{error}</Notice>}<form onSubmit={add}><Field label="Kod"><input name="code" pattern="[a-z][a-z0-9_]{1,63}" required placeholder="research_365"/></Field><Field label="Muddat (kun)"><input name="retention_days" type="number" min="1" max="36500" required/></Field><Button type="submit">Siyosat yaratish</Button></form></aside></div></Page>
}

export function AuditPage(){
 const call=useApi();const {membership}=useAuth();const [filter,setFilter]=useState('');const query=useQuery({queryKey:tenantKey(membership?.organization_id,'audit'),queryFn:()=>call<Record<string,unknown>[]>('/api/v1/audit-events')});const rows=query.data?.filter(row=>JSON.stringify(row).toLowerCase().includes(filter.toLowerCase()))??[]
 return <Page eyebrow="Oxirgi 200 ta event" title="Audit jurnali"><Notice title="Cheklangan server oynasi">Filter faqat server qaytargan oxirgi 200 event ichida ishlaydi.</Notice><Field label="Eventlar ichida qidirish"><input type="search" value={filter} onChange={e=>setFilter(e.target.value)}/></Field>{query.isLoading?<Loading/>:query.error?<ErrorNotice error={query.error}/>:!rows.length?<Empty title="Event topilmadi" icon="scroll-text">Filter mos kelmadi yoki jurnalda hodisa yo‘q.</Empty>:<div className="audit-list">{rows.map((row,index)=><details key={String(row.id??index)}><summary><span>{String(row.action??'event')}</span><Status value={String(row.outcome??'unknown')}/><time>{row.occurred_at?new Date(String(row.occurred_at)).toLocaleString('uz-Latn'):'—'}</time></summary><pre className="safe-json">{JSON.stringify(row,null,2)}</pre></details>)}</div>}</Page>
}

export function MethodologiesPage(){const call=useApi();const {membership}=useAuth();const query=useQuery({queryKey:tenantKey(membership?.organization_id,'methodologies'),queryFn:()=>call<Methodology[]>('/api/v1/methodologies')});return <Page eyebrow="Tasdiqlangan instrumentlar" title="Metodikalar katalogi">{query.isLoading?<Loading/>:query.error?<ErrorNotice error={query.error}/>:!query.data?.length?<Empty title="Katalog bo‘sh" icon="notebook-tabs">Platform administrator metodika va licence’ni nashr qilishi kerak.</Empty>:<div className="ledger">{query.data.map(m=><Link className="ledger-row" key={m.id} to={`/methodologies/${m.id}`}><div><strong>{m.canonical_name}</strong><small><code>{m.methodology_code}</code></small></div><Status value={m.catalog_status}/><span/><span>Versiyalar →</span></Link>)}</div>}</Page>}

export function MethodologyDetail(){const id=location.pathname.split('/').pop()??'';const call=useApi();const {membership}=useAuth();const query=useQuery({queryKey:tenantKey(membership?.organization_id,'methodology',id),queryFn:()=>call<{canonical_name:string;purpose_summary:string;versions:{id:string;version_code:string;lifecycle_status:string;estimated_minutes:number;licence:{status:string;content_disclosure_level:string}|null}[]}>(`/api/v1/methodologies/${id}`)});return <Page title={query.data?.canonical_name??'Metodika'}>{query.isLoading?<Loading/>:query.error?<ErrorNotice error={query.error}/>:<><p className="lead">{query.data?.purpose_summary}</p><div className="ledger">{query.data?.versions.map(v=><div className="ledger-row" key={v.id}><strong>v{v.version_code}</strong><span>{v.estimated_minutes} daqiqa</span><Status value={v.lifecycle_status}/><span>{v.licence?.status??'licence yo‘q'} · {v.licence?.content_disclosure_level??'—'}</span></div>)}</div></>}</Page>}

export function RegistryPage(){
 const {me}=useAuth();const call=useApi();const qc=useQueryClient();const [error,setError]=useState('');const [selected,setSelected]=useState('');const methodologies=useQuery({queryKey:['registry-methodologies'],queryFn:()=>call<Methodology[]>('/api/v1/methodologies')})
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await call('/api/v1/methodologies',{method:'POST',bodyJson:{methodology_code:f.get('methodology_code'),canonical_name:f.get('canonical_name'),purpose_summary:f.get('purpose_summary'),owner_name:f.get('owner_name'),source_reference:f.get('source_reference')}});await qc.invalidateQueries({queryKey:['registry-methodologies']});e.currentTarget.reset()}catch(err){setError(safeMessage(err))}}
 if(!me?.is_platform_admin)return <Page title="Platform registry"><Notice tone="danger" title="Ruxsat yo‘q">Bu hudud faqat platform administratoriga ochiq.</Notice></Page>
 return <Page eyebrow="Global registry" title="Metodika publish pipeline"><Notice tone="warning" title="Ketma-ket gate">Metodika → version snapshot → licence revision → publish. Har bosqich serverda tekshiriladi.</Notice>{error&&<Notice tone="danger" title="Registry amali tugamadi">{error}</Notice>}<div className="workbench-grid"><section><h2>Metodikalar</h2>{methodologies.isLoading?<Loading/>:<div className="ledger">{methodologies.data?.map(m=><button className={`ledger-row ${selected===m.id?'selected':''}`} key={m.id} onClick={()=>setSelected(m.id)}><strong>{m.canonical_name}</strong><code>{m.methodology_code}</code><Status value={m.catalog_status}/><span>Tanlash</span></button>)}</div>}</section><aside className="inspector"><h2>Metodika yaratish</h2><form onSubmit={create}><Field label="Kod"><input name="methodology_code" required pattern="[a-z][a-z0-9_]{1,63}"/></Field><Field label="Canonical nom"><input name="canonical_name" required/></Field><Field label="Maqsad"><textarea name="purpose_summary" required/></Field><Field label="Huquq egasi"><input name="owner_name" required/></Field><Field label="Manba"><input name="source_reference" required/></Field><Button type="submit">Metodika yaratish</Button></form></aside></div>{selected&&<RegistryPipeline methodologyId={selected} onError={setError}/>}</Page>
}

function RegistryPipeline({methodologyId,onError}:{methodologyId:string;onError:(value:string)=>void}){
 const call=useApi();const [versionId,setVersionId]=useState('');const [licenced,setLicenced]=useState(false)
 async function version(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await call<{id:string}>(`/api/v1/methodologies/${methodologyId}/versions`,{method:'POST',bodyJson:{version_code:f.get('version_code'),estimated_minutes:Number(f.get('estimated_minutes')),snapshot:JSON.parse(String(f.get('snapshot'))),default_locale:'uz-Latn',supported_locales:['uz-Latn'],target_population:{adults_only:true,min_age:18},disclaimer_i18n:{'uz-Latn':'Bu natija tibbiy tashxis emas.'}}});setVersionId(data.id)}catch(err){onError(safeMessage(err))}}
 async function licence(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await call(`/api/v1/methodology-versions/${versionId}/licences`,{method:'POST',bodyJson:{status:'verified',copyright_status:f.get('copyright_status'),rights_holder:f.get('rights_holder'),evidence_reference:f.get('evidence_reference'),allowed_use_types:['research'],allowed_org_types:['research_center','university','psychology_center'],allowed_regions:['GLOBAL'],content_disclosure_level:f.get('disclosure'),allow_item_display:f.get('allow_item_display')==='on',allow_item_export:false,allow_trace_item_values:false,valid_from:f.get('valid_from'),valid_until:null,required_disclaimer_i18n:{'uz-Latn':'Bu natija tibbiy tashxis emas.'},restrictions_i18n:{'uz-Latn':'Faqat professional tadqiqot kontekstida.'},change_reason:'Dastlabki tasdiqlangan licence'}});setLicenced(true)}catch(err){onError(safeMessage(err))}}
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await call(`/api/v1/methodology-versions/${versionId}/publish`,{method:'POST',bodyJson:{reason:f.get('reason')}});onError('')}catch(err){onError(safeMessage(err))}}
 return <section className="pipeline"><h2>Publish pipeline</h2><div className="pipeline-grid"><form onSubmit={version}><span className="step-index">01</span><h3>Version snapshot</h3><Field label="Semver"><input name="version_code" pattern="\d+\.\d+\.\d+" required/></Field><Field label="Daqiqa"><input name="estimated_minutes" type="number" min="1" required/></Field><Field label="Snapshot JSON"><textarea name="snapshot" rows={8} required/></Field><Button type="submit">Version yaratish</Button></form><form onSubmit={licence} aria-disabled={!versionId}><span className="step-index">02</span><h3>Licence revision</h3><Field label="Copyright"><select name="copyright_status"><option value="permission_granted">Ruxsat olingan</option><option value="public_domain">Public domain</option><option value="copyrighted">Copyrighted</option></select></Field><Field label="Huquq egasi"><input name="rights_holder" required/></Field><Field label="Dalil manbasi"><input name="evidence_reference" required/></Field><Field label="Disclosure"><select name="disclosure"><option value="derived_only">Derived only</option><option value="full">Full</option><option value="summary_only">Summary only</option></select></Field><Field label="Boshlanish"><input name="valid_from" type="date" required/></Field><label className="choice"><input name="allow_item_display" type="checkbox"/> Item promptlarni ko‘rsatish</label><Button type="submit" disabled={!versionId}>Licence yaratish</Button></form><form onSubmit={publish} aria-disabled={!licenced}><span className="step-index">03</span><h3>Publish gate</h3><Field label="Publish sababi"><textarea name="reason" required/></Field><Button type="submit" disabled={!licenced}>Nashr qilish</Button></form></div></section>
}
