import { useState, type FormEvent } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { api, safeMessage } from '../lib/api'
import { bootstrapEnabled, registrationEnabled } from '../lib/features'
import { useAuth } from '../context/AuthContext'
import { Button, ErrorSummary, Field, Notice } from '../components/UI'

interface Token {access_token:string}
export function LoginPage(){
  const {token,setSession}=useAuth();const navigate=useNavigate();const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  if(token)return <Navigate to="/researches" replace/>
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const result=await api<Token>('/api/v1/auth/login',{method:'POST',bodyJson:{email:form.get('email'),password:form.get('password')}});await setSession(result.access_token);navigate('/researches')}catch(err){setError(safeMessage(err))}finally{setBusy(false)}}
  return <AuthFrame label="Professional tadqiqot muhiti" title="Ish maydoniga kiring"><form onSubmit={submit} aria-describedby={error?'login-error':undefined}><ErrorSummary id="login-error" error={error} title="Kirish amalga oshmadi"/><Field label="Email"><input name="email" type="email" autoComplete="email" required autoFocus/></Field><Field label="Parol"><input name="password" type="password" autoComplete="current-password" required/></Field><Button type="submit" disabled={busy}>{busy?'Tekshirilmoqda…':'Kirish'}</Button><p className="auth-links">{registrationEnabled()&&<Link to="/register">Tashkilot yaratish</Link>}{bootstrapEnabled()&&<Link to="/setup/bootstrap">Platformani sozlash</Link>}</p></form></AuthFrame>
}
export function RegisterPage(){
 const {setSession}=useAuth();const navigate=useNavigate();const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const result=await api<Token>('/api/v1/auth/register',{method:'POST',bodyJson:{email:f.get('email'),full_name:f.get('full_name'),password:f.get('password'),organization_name:f.get('organization_name'),organization_code:f.get('organization_code'),org_type:f.get('org_type'),region:f.get('region')}});await setSession(result.access_token);navigate('/researches')}catch(err){setError(safeMessage(err))}finally{setBusy(false)}}
 return <AuthFrame label="Yangi tashkilot" title="Tadqiqot muhitini oching"><form onSubmit={submit} aria-describedby={error?'register-error':undefined}><ErrorSummary id="register-error" error={error} title="Tashkilot yaratilmadi"/><div className="form-grid"><Field label="To‘liq ism"><input name="full_name" required/></Field><Field label="Email"><input name="email" type="email" required/></Field><Field label="Tashkilot nomi"><input name="organization_name" required/></Field><Field label="Tashkilot kodi" hint="Kichik harf, raqam va pastki chiziq"><input name="organization_code" pattern="[a-z][a-z0-9_]{1,63}" required/></Field><Field label="Tashkilot turi"><select name="org_type"><option value="research_center">Tadqiqot markazi</option><option value="university">Universitet</option><option value="psychology_center">Psixologik markaz</option></select></Field><Field label="Hudud"><input name="region" defaultValue="GLOBAL" required/></Field></div><Field label="Parol" hint="Kamida 12 ta belgi"><input name="password" type="password" minLength={12} required/></Field><Button type="submit" disabled={busy}>{busy?'Yaratilmoqda…':'Tashkilot yaratish'}</Button><p><Link to="/login">Kirishga qaytish</Link></p></form></AuthFrame>
}
export function BootstrapPage(){
 const {setSession}=useAuth();const navigate=useNavigate();const [error,setError]=useState('')
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const result=await api<Token>('/api/v1/auth/bootstrap',{method:'POST',bodyJson:{email:f.get('email'),full_name:f.get('full_name'),password:f.get('password'),bootstrap_token:f.get('bootstrap_token')||null}});await setSession(result.access_token);navigate('/registry')}catch(err){setError(safeMessage(err))}}
 return <AuthFrame label="Bir martalik sozlash" title="Platformani ishga tayyorlang"><form onSubmit={submit} aria-describedby={error?'bootstrap-error':undefined}><Notice tone="warning" title="Deployment operator uchun">Bu amal faqat bo‘sh instance’da bir marta bajariladi.</Notice><ErrorSummary id="bootstrap-error" error={error} title="Sozlash tugamadi"/><Field label="Administrator ismi"><input name="full_name" required/></Field><Field label="Email"><input name="email" type="email" required/></Field><Field label="Parol"><input name="password" type="password" minLength={12} required/></Field><Field label="Bootstrap token"><input name="bootstrap_token" type="password"/></Field><Button type="submit">Ishga tayyorlash</Button></form></AuthFrame>
}
function AuthFrame({label,title,children}:{label:string;title:string;children:React.ReactNode}){return <main className="auth-page"><section className="auth-identity"><div className="auth-wordmark"><span className="registration-mark"/>PSYCHOGRAM</div><p>{label}</p><h1>{title}</h1><div className="instrument-lines" aria-hidden="true"/></section><section className="auth-form">{children}</section></main>}
