import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Button, ConfirmAction, Drawer, Empty, ErrorNotice, ErrorSummary, Field, LiveStatus, Loading, Notice, Pagination, Status } from '../components/UI'
import { useApi, useAuth } from '../context/AuthContext'
import { safeMessage } from '../lib/api'
import { can, canAccessPii } from '../lib/capabilities'
import { tenantKey } from '../lib/queryKeys'
import type { Page, Participant } from '../types'

interface ConsentItem { id:string; participant_id:string; status:string; reference:string; version:string; obtained_at:string; basis:string|null; record_version:number; created_at:string }
interface ConsentHistory { current:ConsentItem|null; history:ConsentItem[] }
interface PII { participant_id:string; fields:Record<string,string>; algorithm:string; key_version:string; updated_at:string }
const LIMIT=20

export function ParticipantsPage(){
  const {researchId=''}=useParams();const call=useApi();const qc=useQueryClient();const {membership}=useAuth();const [drawer,setDrawer]=useState(false);const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);const [error,setError]=useState('')
  const prefix=tenantKey(membership?.organization_id,'participants',researchId);const participants=useQuery({queryKey:[...prefix,query,offset,LIMIT],queryFn:()=>call<Page<Participant>>(`/api/v1/researches/${researchId}/participants?limit=${LIMIT}&offset=${offset}&query=${encodeURIComponent(query)}`)})
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{await call(`/api/v1/researches/${researchId}/participants`,{method:'POST',bodyJson:{external_code:f.get('external_code')}});await qc.invalidateQueries({queryKey:prefix});setDrawer(false)}catch(err){setError(safeMessage(err))}}
  return <section className="route-section"><header className="section-header"><div><p className="eyebrow">Pseudonim avval</p><h2>Ishtirokchilar va consent</h2></div>{can(membership?.role,'participant:write')&&<Button onClick={()=>setDrawer(true)} icon="user-round">Ishtirokchi qo‘shish</Button>}</header><Notice tone="privacy" title="Maxfiylik chegarasi">Ro‘yxatda shaxsni aniqlovchi ma’lumot emas, faqat tashqi pseudonim kod ishlatiladi.</Notice><Field label="Pseudonim kod bo‘yicha qidirish"><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}} placeholder="Masalan, P-014"/></Field>{participants.isLoading?<Loading/>:participants.error?<ErrorNotice error={participants.error}/>:!participants.data?.items.length?<Empty title="Ishtirokchi topilmadi" icon="user-round">Yangi pseudonim kod kiriting yoki qidiruvni tozalang.</Empty>:<><div className="data-table-wrap"><table><thead><tr><th scope="col">Kod</th><th scope="col">Processing</th><th scope="col">Consent</th><th scope="col">PII</th><th scope="col">Yaratilgan</th><th scope="col">Amal</th></tr></thead><tbody>{participants.data.items.map(p=><tr key={p.id}><td data-label="Kod"><strong>{p.external_code}</strong></td><td data-label="Processing"><Status value={p.processing_status}/></td><td data-label="Consent"><Status value={p.current_consent_status}/></td><td data-label="PII">{p.has_pii?'Mavjud':'Yo‘q'}</td><td data-label="Yaratilgan">{new Intl.DateTimeFormat('uz-Latn').format(new Date(p.created_at))}</td><td data-label="Amal"><Link to={p.id}>Ochish →</Link></td></tr>)}</tbody></table></div><Pagination offset={participants.data.offset} limit={participants.data.limit} total={participants.data.total} onChange={setOffset}/></>}<Drawer open={drawer} title="Ishtirokchi qo‘shish" onClose={()=>setDrawer(false)}><form onSubmit={add} aria-describedby={error?'participant-error':undefined}><ErrorSummary id="participant-error" error={error} title="Saqlanmadi"/><Field label="Tashqi pseudonim kod" hint="PII yoki to‘liq ism kiritmang"><input name="external_code" required autoFocus/></Field><Button type="submit">Saqlash</Button></form></Drawer></section>
}

export function ParticipantDetail(){
  const {researchId='',participantId=''}=useParams();const call=useApi();const qc=useQueryClient();const {membership}=useAuth();const org=membership?.organization_id
  const [error,setError]=useState('');const [pii,setPii]=useState<PII|null>(null);const [showPii,setShowPii]=useState(false);const [confirmDelete,setConfirmDelete]=useState(false);const [deleting,setDeleting]=useState(false);const [success,setSuccess]=useState('')
  const participantKey=tenantKey(org,'participant',researchId,participantId);const consentKey=tenantKey(org,'consents',researchId,participantId)
  const participant=useQuery({queryKey:participantKey,queryFn:()=>call<Participant>(`/api/v1/researches/${researchId}/participants/${participantId}`)});const consents=useQuery({queryKey:consentKey,queryFn:()=>call<ConsentHistory>(`/api/v1/researches/${researchId}/participants/${participantId}/consents`)})
  useEffect(()=>()=>{setPii(null);setShowPii(false);setConfirmDelete(false)},[org])
  async function record(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setError('');try{await call(`/api/v1/participants/${participantId}/consents`,{method:'POST',bodyJson:{status:f.get('status'),reference:f.get('reference'),version:f.get('version'),obtained_at:new Date(String(f.get('obtained_at'))).toISOString(),basis:f.get('basis')||null}});await qc.invalidateQueries({queryKey:consentKey});await qc.invalidateQueries({queryKey:tenantKey(org,'participants',researchId)})}catch(err){setError(safeMessage(err))}}
  async function reveal(){setError('');setSuccess('');try{const data=await call<PII>(`/api/v1/researches/${researchId}/participants/${participantId}/pii`);setPii(data);setShowPii(true)}catch(err){setError(safeMessage(err))}}
  function hidePii(){setPii(null);setShowPii(false);setConfirmDelete(false);setSuccess('PII plaintext brauzer holatidan tozalandi.')}
  async function savePii(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const fields=Object.fromEntries([...f.entries()].filter(([,v])=>String(v).trim()));setError('');setSuccess('');try{const data=await call<PII>(`/api/v1/researches/${researchId}/participants/${participantId}/pii`,{method:'PUT',bodyJson:{fields}});setPii(data);setShowPii(true);setSuccess('PII serverda shifrlab saqlandi.');await qc.invalidateQueries({queryKey:tenantKey(org,'participants',researchId)})}catch(err){setError(safeMessage(err))}}
  async function deletePii(){setDeleting(true);setError('');setSuccess('');try{await call(`/api/v1/researches/${researchId}/participants/${participantId}/pii`,{method:'DELETE'});setPii(null);setShowPii(false);setConfirmDelete(false);setSuccess('PII yozuvi o‘chirildi; ochilgan plaintext holati tozalandi.');await Promise.all([qc.invalidateQueries({queryKey:participantKey}),qc.invalidateQueries({queryKey:tenantKey(org,'participants',researchId)})])}catch(err){setError(safeMessage(err))}finally{setDeleting(false)}}
  if(participant.isLoading)return <Loading/>;if(participant.error)return <ErrorNotice error={participant.error}/>
  const writable=can(membership?.role,'participant:write'),piiAllowed=canAccessPii(membership)
  return <section className="route-section"><Link className="back-action" to="..">← Ishtirokchilar</Link><header className="section-header"><div><p className="eyebrow">Participant</p><h2>{participant.data?.external_code}</h2></div><Status value={participant.data?.processing_status}/></header><ErrorSummary error={error}/>{success&&<LiveStatus><Notice tone="success" title="Server tasdiqladi">{success}</Notice></LiveStatus>}<div className="workbench-grid"><section>{writable&&<><h3>Rozilikni qayd etish</h3><form onSubmit={record}><div className="form-grid"><Field label="Holat"><select name="status"><option value="granted">Rozilik berildi</option><option value="declined">Rad etildi</option><option value="withdrawn">Qaytarib olindi</option><option value="not_required_with_basis">Asos bilan talab qilinmaydi</option></select></Field><Field label="Olingan vaqt"><input name="obtained_at" type="datetime-local" required/></Field><Field label="Manba"><input name="reference" required/></Field><Field label="Versiya"><input name="version" required/></Field></div><Field label="Huquqiy/asos izohi"><textarea name="basis" rows={2}/></Field><Button type="submit" icon="file-signature">Rozilikni qayd etish</Button></form></>}<h3>Consent tarixi</h3>{consents.isLoading?<Loading/>:!consents.data?.history.length?<p className="muted">Hali qayd yo‘q.</p>:<ol className="timeline">{consents.data.history.map(c=><li key={c.id}><Status value={c.status}/><strong>v{c.record_version} · {c.reference}</strong><small>{new Date(c.obtained_at).toLocaleString('uz-Latn')}</small></li>)}</ol>}</section><aside className="privacy-panel"><h3>Shaxsni aniqlovchi ma’lumot</h3>{!piiAllowed?<Notice tone="privacy" title="PII ruxsati yo‘q">Qiymatlar serverdan so‘ralmaydi va DOMga kelmaydi.</Notice>:!showPii?<Button variant="secondary" icon="shield" onClick={reveal}>Audit bilan ko‘rsatish</Button>:<form onSubmit={savePii}><Field label="To‘liq ism"><input name="full_name" defaultValue={pii?.fields.full_name}/></Field><Field label="Email"><input name="email" type="email" defaultValue={pii?.fields.email}/></Field><Field label="Telefon"><input name="phone" defaultValue={pii?.fields.phone}/></Field><Field label="Tug‘ilgan sana"><input name="date_of_birth" type="date" defaultValue={pii?.fields.date_of_birth}/></Field><div className="button-row"><Button type="submit">Shifrlab saqlash</Button><Button type="button" variant="secondary" onClick={hidePii}>PIIni yashirish</Button><Button type="button" variant="danger" onClick={()=>setConfirmDelete(true)}>PII yozuvini o‘chirish</Button></div></form>}</aside></div><ConfirmAction open={confirmDelete} title="PII yozuvini o‘chirish" description="Shifrlangan PII yozuvi qaytarib bo‘lmaydigan tarzda o‘chiriladi. Legal hold mavjud bo‘lsa server amalni bloklaydi." confirmLabel="Ha, PII yozuvini o‘chirish" onConfirm={deletePii} onCancel={()=>setConfirmDelete(false)} busy={deleting}/></section>
}
