import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { Link, NavLink, Outlet, useNavigate, useParams } from 'react-router-dom'
import { Button, Empty, ErrorNotice, ErrorSummary, Field, Loading, Notice, Page, Status } from '../components/UI'
import { useApi, useAuth } from '../context/AuthContext'
import { safeMessage } from '../lib/api'
import { can } from '../lib/capabilities'
import { csvImportEnabled } from '../lib/features'
import { tenantKey } from '../lib/queryKeys'
import type { Research, Retention, Version } from '../types'

export function ResearchList(){
 const call=useApi();const {membership}=useAuth();const key=tenantKey(membership?.organization_id,'researches');const query=useQuery({queryKey:key,queryFn:()=>call<Research[]>('/api/v1/researches')})
 return <Page eyebrow="Tadqiqot daftari" title="Tadqiqotlar" actions={can(membership?.role,'research:create')?<Link className="button primary" to="/researches/new">Yangi tadqiqot</Link>:undefined}>{query.isLoading?<Loading/>:query.error?<ErrorNotice error={query.error}/>:!query.data?.length?<Empty icon="flask-conical" title="Tadqiqot hali yo‘q" action={can(membership?.role,'research:create')?<Link className="button primary" to="/researches/new">Birinchi qoralamani yarating</Link>:undefined}>Metodika va retention siyosati tayyor bo‘lgach tadqiqot ochiladi.</Empty>:<div className="ledger"><div className="ledger-head"><span>Nomi va maqsadi</span><span>Maxfiylik</span><span>Holat</span><span>Amal</span></div>{query.data.map(item=><Link to={`/researches/${item.id}`} className="ledger-row" key={item.id}><div><strong>{item.name}</strong><small>{item.purpose}</small></div><span>{item.pii_mode}</span><Status value={item.status}/><span aria-hidden>→</span></Link>)}</div>}</Page>
}

export function ResearchCreate(){
 const call=useApi();const navigate=useNavigate();const qc=useQueryClient();const {membership}=useAuth();const [useType,setUseType]=useState('research');const [versionId,setVersionId]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const policies=useQuery({queryKey:tenantKey(membership?.organization_id,'retention'),queryFn:()=>call<Retention[]>('/api/v1/retention-policies')});const versions=useQuery({queryKey:tenantKey(membership?.organization_id,'eligible-versions',useType),queryFn:()=>call<Version[]>(`/api/v1/methodology-versions/eligible?use_type=${useType}`)});const selected=versions.data?.find(item=>item.id===versionId)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const result=await call<Research>('/api/v1/researches',{method:'POST',bodyJson:{name:f.get('name'),purpose:f.get('purpose'),methodology_version_id:f.get('methodology_version_id'),pii_mode:f.get('pii_mode'),consent_reference:f.get('consent_reference'),consent_version:f.get('consent_version'),retention_policy_id:f.get('retention_policy_id'),use_type:f.get('use_type'),norm_selection:{}}});await qc.invalidateQueries({queryKey:tenantKey(membership?.organization_id,'researches')});navigate(`/researches/${result.id}`)}catch(err){setError(safeMessage(err))}finally{setBusy(false)}}
 const unavailable=!versions.isLoading&&!versions.data?.length?'Mos, nashr qilingan va licence tasdiqlangan metodika yo‘q.':!policies.isLoading&&!policies.data?.length?'Avval retention siyosatini yarating.':''
 return <Page eyebrow="Yangi instrument" title="Tadqiqot qoralamasini yarating"><form className="form-panel" onSubmit={submit} aria-describedby={error?'research-error':undefined}><ErrorSummary id="research-error" error={error} title="Qoralama yaratilmadi"/><section><h2>01 · Maqsad</h2><Field label="Tadqiqot nomi"><input name="name" required maxLength={200}/></Field><Field label="Maqsad"><textarea name="purpose" required maxLength={2000} rows={4}/></Field><Field label="Foydalanish turi"><select name="use_type" value={useType} onChange={e=>{setUseType(e.target.value);setVersionId('')}}><option value="research">Tadqiqot</option><option value="education">Ta’lim</option><option value="clinical">Klinik kontekst</option></select></Field></section><section><h2>02 · Metodika</h2>{versions.isLoading?<Loading label="Mos metodikalar tekshirilmoqda"/>:versions.error?<ErrorNotice error={versions.error}/>:<Field label="Nashr qilingan versiya"><select name="methodology_version_id" required value={versionId} onChange={event=>setVersionId(event.target.value)}><option value="" disabled>Versiyani tanlang</option>{versions.data?.map(v=><option key={v.id} value={v.id}>v{v.version_code} · {v.estimated_minutes} daqiqa · {v.licence?.status}</option>)}</select></Field>}{selected&&<aside className="licence-review" aria-label="Tanlangan licence sharhi"><h3>Server licence snapshoti</h3><dl><dt>Disclosure</dt><dd>{selected.licence?.content_disclosure_level??'—'}</dd><dt>Cheklovlar</dt><dd>{selected.licence?.restrictions_i18n?.['uz-Latn']??'Server cheklov bermagan.'}</dd><dt>Disclaimer</dt><dd>{selected.disclaimer_i18n?.['uz-Latn']??'Server disclaimer bermagan.'}</dd></dl></aside>}</section><section><h2>03 · Maxfiylik va rozilik</h2><Field label="PII rejimi"><select name="pii_mode" defaultValue="pseudonymous"><option value="pseudonymous">Pseudonim — tavsiya etiladi</option><option value="anonymous">Anonim</option><option value="identified">Identifikatsiyalangan (PII konfiguratsiyasi talab qiladi)</option></select></Field><div className="form-grid"><Field label="Rozilik manbasi"><input name="consent_reference" required placeholder="ethics/consent-2026"/></Field><Field label="Rozilik versiyasi"><input name="consent_version" required placeholder="1.0"/></Field></div><Field label="Retention siyosati">{policies.isLoading?<span>Yuklanmoqda…</span>:<select name="retention_policy_id" required defaultValue=""><option value="" disabled>Siyosatni tanlang</option>{policies.data?.map(p=><option key={p.id} value={p.id}>{p.code} · {p.retention_days} kun</option>)}</select>}</Field></section><Notice title="Faollashtirishdan oldin">Qoralama yaratilgach metodika, licence va maxfiylik sozlamalarini yana tekshiring.</Notice>{unavailable&&<Notice tone="warning" title="Draft hozir yaratilmaydi">{unavailable}</Notice>}<Button type="submit" disabled={busy||Boolean(unavailable)}>{busy?'Yaratilmoqda…':'Draft yaratish'}</Button></form></Page>
}

export function ResearchLayout(){
 const {researchId=''}=useParams();const call=useApi();const qc=useQueryClient();const navigate=useNavigate();const {membership}=useAuth();const [error,setError]=useState('');const key=tenantKey(membership?.organization_id,'researches');const query=useQuery({queryKey:key,queryFn:()=>call<Research[]>('/api/v1/researches')});const research=query.data?.find(r=>r.id===researchId)
 async function activate(){try{await call(`/api/v1/researches/${researchId}/activate`,{method:'POST'});await qc.invalidateQueries({queryKey:key})}catch(err){setError(safeMessage(err))}}
 if(query.isLoading)return <Loading/>;if(!research)return <Page title="Tadqiqot topilmadi"><Empty title="Bu tenantda tadqiqot yo‘q" icon="circle-x">Ro‘yxat yangilangan yoki sizda ruxsat bo‘lmasligi mumkin.</Empty></Page>
 return <div><header className="research-header"><button className="back-link" aria-label="Tadqiqotlar ro‘yxatiga qaytish" onClick={()=>navigate('/researches')}>← Ro‘yxat</button><div><p className="eyebrow">Tadqiqot workbench</p><h1>{research.name}</h1><p>{research.purpose}</p></div><div><Status value={research.status}/>{research.status==='draft'&&can(membership?.role,'research:activate')&&<Button onClick={activate} icon="circle-check">Faollashtirish</Button>}</div></header><ErrorSummary error={error}/><div className="context-strip"><span>Metodika <code>{research.methodology_version_id.slice(0,8)}…</code></span><span>Maxfiylik <strong>{research.pii_mode}</strong></span><span>Tenant <code>{research.tenant_id.slice(0,8)}…</code></span></div><nav className="tabs"><NavLink end to={`/researches/${researchId}`}>Umumiy</NavLink><NavLink to="participants">Ishtirokchilar</NavLink><NavLink to="responses">Javoblar</NavLink>{csvImportEnabled()&&can(membership?.role,'response:write')&&<NavLink to="import">CSV import</NavLink>}{can(membership?.role,'result:read')&&<NavLink to="results">Natijalar</NavLink>}</nav><Outlet context={{research}}/></div>
}
export function ResearchOverview(){const {researchId}=useParams();const {membership}=useAuth();return <div className="workbench-grid"><section><h2>Ish maydoni</h2><div className="action-list"><Link to="participants"><span>01</span><div><strong>Ishtirokchi va rozilik</strong><small>Pseudonim kod, consent tarixi va PII chegarasi</small></div><b>→</b></Link><Link to="responses"><span>02</span><div><strong>Javoblarni ko‘rish</strong><small>Revision va canonical validation</small></div><b>→</b></Link>{csvImportEnabled()&&can(membership?.role,'response:write')&&<Link to="import"><span>03</span><div><strong>CSV orqali kiritish</strong><small>Avval preview, keyin server tasdiqlashi</small></div><b>→</b></Link>}{can(membership?.role,'result:read')&&<Link to="results"><span>04</span><div><strong>Natija va hisob izi</strong><small>Provenance, talqin va disclosure darajasi</small></div><b>→</b></Link>}</div></section><aside className="inspector"><h2>Kontekst</h2><dl><dt>Research ID</dt><dd><code>{researchId}</code></dd><dt>Natija chegarasi</dt><dd>Ushbu platforma tibbiy tashxis qo‘ymaydi.</dd></dl></aside></div>}
