import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { Link, NavLink, Outlet, useLocation, useNavigate, useParams } from 'react-router-dom'
import { Button, Empty, ErrorNotice, ErrorSummary, Field, Loading, Notice, Page, Status } from '../components/UI'
import { useApi, useAuth } from '../context/AuthContext'
import { safeMessage } from '../lib/api'
import { can } from '../lib/capabilities'
import { csvImportEnabled } from '../lib/features'
import { tenantKey } from '../lib/queryKeys'
import type { Research, Retention, Version } from '../types'

export function ResearchList(){
 const call=useApi();const {membership}=useAuth();const key=tenantKey(membership?.organization_id,'researches');const query=useQuery({queryKey:key,queryFn:()=>call<Research[]>('/api/v1/researches')})
 return <Page eyebrow="Tadqiqot daftari" title="Tadqiqotlar" actions={can(membership?.role,'research:create')?<Link className="button primary" to="/researches/new">Yangi tadqiqot</Link>:undefined}>{query.isLoading?<Loading/>:query.error?<ErrorNotice error={query.error}/>:!query.data?.length?<Empty icon="flask-conical" title="Tadqiqot hali yo‘q" action={can(membership?.role,'research:create')?<Link className="button primary" to="/researches/new">Birinchi qoralamani yarating</Link>:undefined}>Metodika va retention siyosati tayyor bo‘lgach tadqiqot ochiladi.</Empty>:<div className="ledger"><div className="ledger-head"><span>Nomi va maqsadi</span><span>Maxfiylik</span><span>Holat</span><span>Amal</span></div>{query.data.map(item=><Link to={`/researches/${item.id}`} className="ledger-row" key={item.id}><div><strong>{item.name}</strong><small>{item.purpose}</small></div><span>{item.pii_mode}</span><Status value={item.status}/><span aria-hidden>→</span></Link>)}</div>}</Page>
}

export function ResearchCreate(){
 const call=useApi();const navigate=useNavigate();const qc=useQueryClient();const {membership}=useAuth();const [versionId,setVersionId]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const policies=useQuery({queryKey:tenantKey(membership?.organization_id,'retention'),queryFn:()=>call<Retention[]>('/api/v1/retention-policies')});const versions=useQuery({queryKey:tenantKey(membership?.organization_id,'eligible-versions','research'),queryFn:()=>call<Version[]>('/api/v1/methodology-versions/eligible?use_type=research')});const selected=versions.data?.find(item=>item.id===versionId)
 const activePolicies=policies.data?.filter(policy=>policy.active)??[];const onlyPolicy=activePolicies.length===1?activePolicies[0]:undefined
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);let created:Research
  try{created=await call<Research>('/api/v1/researches',{method:'POST',bodyJson:{name:f.get('name'),purpose:f.get('purpose'),methodology_version_id:f.get('methodology_version_id'),pii_mode:'pseudonymous',consent_reference:f.get('consent_reference'),consent_version:f.get('consent_version'),retention_policy_id:onlyPolicy?.id??f.get('retention_policy_id'),use_type:'research',norm_selection:{}}})}catch(err){setError(safeMessage(err));setBusy(false);return}
  // The research now exists; if starting it fails, continue with that same research instead of creating another.
  let activationError=''
  try{await call(`/api/v1/researches/${created.id}/activate`,{method:'POST'})}catch(err){activationError=safeMessage(err)}
  await qc.invalidateQueries({queryKey:tenantKey(membership?.organization_id,'researches')});setBusy(false);navigate(`/researches/${created.id}`,{state:activationError?{activationError}:undefined})}
 const unavailable=!versions.isLoading&&!versions.data?.length?'Tashkilotingiz uchun foydalanishga ruxsat berilgan metodika hali yo‘q. Administratorga murojaat qiling.':!policies.isLoading&&!activePolicies.length?'Ma’lumotlarni saqlash muddati hali belgilanmagan. Administratorga murojaat qiling.':''
 return <Page eyebrow="Yangi tadqiqot" title="Tadqiqotni yarating va boshlang"><form className="form-panel" onSubmit={submit} aria-describedby={error?'research-error':undefined}><ErrorSummary id="research-error" error={error} title="Tadqiqot yaratilmadi"/><section><h2>01 · Maqsad</h2><Field label="Tadqiqot nomi"><input name="name" required maxLength={200}/></Field><Field label="Maqsad"><textarea name="purpose" required maxLength={2000} rows={4}/></Field></section><section><h2>02 · Metodika</h2>{versions.isLoading?<Loading label="Metodikalar yuklanmoqda"/>:versions.error?<ErrorNotice error={versions.error}/>:<Field label="Metodika"><select name="methodology_version_id" required value={versionId} onChange={event=>setVersionId(event.target.value)}><option value="" disabled>Metodikani tanlang</option>{versions.data?.map(v=><option key={v.id} value={v.id}>{v.methodology_name} · v{v.version_code} · {v.estimated_minutes} daqiqa</option>)}</select></Field>}{selected&&<aside className="licence-review" aria-label="Metodikadan foydalanish shartlari"><h3>Foydalanish shartlari</h3><dl><dt>Cheklovlar</dt><dd>{selected.licence?.restrictions_i18n?.['uz-Latn']??'Qo‘shimcha cheklov yo‘q.'}</dd><dt>Natija izohi</dt><dd>{selected.disclaimer_i18n?.['uz-Latn']??'Bu natija tibbiy tashxis emas.'}</dd></dl></aside>}</section><section><h2>03 · Rozilik va saqlash</h2><Notice title="Respondentlar kod bilan kiritiladi">Ism, telefon yoki manzil kiritilmaydi; har bir respondent P001 kabi tadqiqot ichidagi kod bilan qayd etiladi.</Notice><div className="form-grid"><Field label="Rozilik hujjati yoki asosi" hint="Masalan, etika qo‘mitasi qarori yoki rozilik shakli nomi"><input name="consent_reference" required maxLength={1000}/></Field><Field label="Rozilik shakli versiyasi"><input name="consent_version" required maxLength={64} placeholder="1.0"/></Field></div>{policies.isLoading?<Loading label="Saqlash muddati yuklanmoqda"/>:onlyPolicy?<p className="muted">Saqlash muddati: <strong>{onlyPolicy.retention_days} kun</strong> (tashkilot standarti)</p>:activePolicies.length>1&&<Field label="Saqlash muddati"><select name="retention_policy_id" required defaultValue=""><option value="" disabled>Muddatni tanlang</option>{activePolicies.map(p=><option key={p.id} value={p.id}>{p.code} · {p.retention_days} kun</option>)}</select></Field>}</section>{unavailable&&<Notice tone="warning" title="Tadqiqotni hozir boshlab bo‘lmaydi">{unavailable}</Notice>}<Button type="submit" disabled={busy||Boolean(unavailable)}>{busy?'Yaratilmoqda…':'Yaratish va boshlash'}</Button></form></Page>
}

export function ResearchLayout(){
 const {researchId=''}=useParams();const call=useApi();const qc=useQueryClient();const navigate=useNavigate();const location=useLocation();const {membership}=useAuth();const [error,setError]=useState(()=>(location.state as {activationError?:string}|null)?.activationError??'');const key=tenantKey(membership?.organization_id,'researches');const query=useQuery({queryKey:key,queryFn:()=>call<Research[]>('/api/v1/researches')});const research=query.data?.find(r=>r.id===researchId)
 async function activate(){setError('');try{await call(`/api/v1/researches/${researchId}/activate`,{method:'POST'});await qc.invalidateQueries({queryKey:key})}catch(err){setError(safeMessage(err))}}
 if(query.isLoading)return <Loading/>;if(!research)return <Page title="Tadqiqot topilmadi"><Empty title="Bu tenantda tadqiqot yo‘q" icon="circle-x">Ro‘yxat yangilangan yoki sizda ruxsat bo‘lmasligi mumkin.</Empty></Page>
 return <div><header className="research-header"><button className="back-link" aria-label="Tadqiqotlar ro‘yxatiga qaytish" onClick={()=>navigate('/researches')}>← Ro‘yxat</button><div><p className="eyebrow">Tadqiqot workbench</p><h1>{research.name}</h1><p>{research.purpose}</p></div><div><Status value={research.status}/>{['draft','ready'].includes(research.status)&&can(membership?.role,'research:activate')&&<Button onClick={activate} icon="circle-check">Tadqiqotni boshlash</Button>}</div></header><ErrorSummary error={error} title="Tadqiqot boshlanmadi"/><div className="context-strip"><span>Metodika <code>{research.methodology_version_id.slice(0,8)}…</code></span><span>Maxfiylik <strong>{research.pii_mode}</strong></span><span>Tenant <code>{research.tenant_id.slice(0,8)}…</code></span></div><nav className="tabs"><NavLink end to={`/researches/${researchId}`}>Umumiy</NavLink><NavLink to="participants">Ishtirokchilar</NavLink><NavLink to="responses">Javoblar</NavLink>{csvImportEnabled()&&can(membership?.role,'response:write')&&<NavLink to="import">CSV import</NavLink>}{can(membership?.role,'result:read')&&<NavLink to="results">Natijalar</NavLink>}</nav><Outlet context={{research}}/></div>
}
export function ResearchOverview(){const {researchId}=useParams();const {membership}=useAuth();return <div className="workbench-grid"><section><h2>Ish maydoni</h2><div className="action-list"><Link to="participants"><span>01</span><div><strong>Ishtirokchi va rozilik</strong><small>Pseudonim kod, consent tarixi va PII chegarasi</small></div><b>→</b></Link><Link to="responses"><span>02</span><div><strong>Javoblarni ko‘rish</strong><small>Revision va canonical validation</small></div><b>→</b></Link>{csvImportEnabled()&&can(membership?.role,'response:write')&&<Link to="import"><span>03</span><div><strong>CSV orqali kiritish</strong><small>Avval preview, keyin server tasdiqlashi</small></div><b>→</b></Link>}{can(membership?.role,'result:read')&&<Link to="results"><span>04</span><div><strong>Natija va hisob izi</strong><small>Provenance, talqin va disclosure darajasi</small></div><b>→</b></Link>}</div></section><aside className="inspector"><h2>Kontekst</h2><dl><dt>Research ID</dt><dd><code>{researchId}</code></dd><dt>Natija chegarasi</dt><dd>Ushbu platforma tibbiy tashxis qo‘ymaydi.</dd></dl></aside></div>}
