import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button, Empty, ErrorNotice, ErrorSummary, Loading, Notice, Page, Pagination, Status } from '../components/UI'
import { useApi, useAuth } from '../context/AuthContext'
import { safeMessage } from '../lib/api'
import { can } from '../lib/capabilities'
import { tenantKey } from '../lib/queryKeys'
import type { Page as DataPage, ResponseDetail, ResponseItem } from '../types'

const LIMIT=20
export function ResponsesPage(){
 const {researchId=''}=useParams();const call=useApi();const {membership}=useAuth();const [offset,setOffset]=useState(0);const key=tenantKey(membership?.organization_id,'responses',researchId,offset,LIMIT);const responses=useQuery({queryKey:key,queryFn:()=>call<DataPage<ResponseItem>>(`/api/v1/researches/${researchId}/responses?limit=${LIMIT}&offset=${offset}`)})
 const writable=can(membership?.role,'response:write')
 return <section className="route-section"><header className="section-header"><div><p className="eyebrow">Respondentlar</p><h2>Javoblar</h2></div>{writable&&<Link className="button primary" to="new">Javob kiritish</Link>}</header>{responses.isLoading?<Loading/>:responses.error?<ErrorNotice error={responses.error}/>:!responses.data?.items.length?<Empty title="Javob hali yo‘q" icon="list-pen" action={writable?<Link className="button primary" to="new">Birinchi javobni kiriting</Link>:undefined}>Respondent kodi, rozilik qaydi va javoblar bitta formada kiritiladi.</Empty>:<><div className="data-table-wrap"><table><thead><tr><th scope="col">Respondent</th><th scope="col">Javob</th><th scope="col">Natija</th><th scope="col">Sana</th><th scope="col">Amal</th></tr></thead><tbody>{responses.data.items.map(r=><tr key={r.id}><td data-label="Respondent"><strong>{r.participant_external_code}</strong></td><td data-label="Javob"><Status value={r.current_revision_status??r.status}/></td><td data-label="Natija"><Status value={r.result_status}/></td><td data-label="Sana">{new Date(r.created_at).toLocaleString('uz-Latn')}</td><td data-label="Amal"><Link to={writable?r.id:`/responses/${r.id}`}>Ochish →</Link>{r.current_result_id&&<> · <Link to={`/results/${r.current_result_id}`}>Natija</Link></>}</td></tr>)}</tbody></table></div><Pagination offset={responses.data.offset} limit={responses.data.limit} total={responses.data.total} onChange={setOffset}/></>}</section>
}

export function ResponseDetailPage(){
 const {responseId=''}=useParams();const call=useApi();const qc=useQueryClient();const navigate=useNavigate();const {membership}=useAuth();const org=membership?.organization_id;const [error,setError]=useState('');
 const key=tenantKey(org,'response',responseId);const response=useQuery({queryKey:key,queryFn:()=>call<ResponseDetail>(`/api/v1/responses/${responseId}`)});const revision=response.data?.current_revision;const summary=useMemo(()=>revision?.validation_summary?JSON.stringify(revision.validation_summary,null,2):'', [revision])
 async function validate(){setError('');try{await call(`/api/v1/responses/${responseId}/validate`,{method:'POST'});await qc.invalidateQueries({queryKey:key})}catch(err){setError(safeMessage(err))}}
 async function calculate(){if(!response.data?.current_revision_id)return;setError('');try{const result=await call<{id:string}>(`/api/v1/researches/${response.data.research_id}/calculations`,{method:'POST',bodyJson:{response_revision_id:response.data.current_revision_id,idempotency_key:`calc-${response.data.current_revision_id}`}});navigate(`/results/${result.id}`)}catch(err){setError(safeMessage(err))}}
 if(response.isLoading)return <Loading/>;if(response.error)return <ErrorNotice error={response.error}/>;if(!response.data)return null
 return <Page eyebrow={`Participant ${response.data.participant_external_code}`} title={`Javob · revision ${revision?.revision_number??'—'}`} actions={<Status value={revision?.status??response.data.status}/>}><div className="provenance-strip"><span>Response <code>{responseId.slice(0,8)}…</code></span><span>Lock <strong>{response.data.lock_version}</strong></span><span>Hash <code>{revision?.answer_payload_hash.slice(0,12)??'—'}…</code></span></div><ErrorSummary error={error}/><div className="workbench-grid"><section><h2>Canonical validation</h2>{summary?<pre className="safe-json">{summary}</pre>:<p className="muted">Server validation xulosasi hali yo‘q.</p>}<div className="button-row">{revision?.status!=='validated'&&can(membership?.role,'response:write')&&<Button icon="list-checks" onClick={validate}>Serverda tekshirish</Button>}{revision?.status==='validated'&&can(membership?.role,'result:calculate')&&<Button icon="sigma" onClick={calculate}>Natijani hisoblash</Button>}</div>{revision?.status!=='validated'&&!can(membership?.role,'response:write')&&<Notice title="Faqat o‘qish">Sizning rolingiz revisionni tekshira olmaydi.</Notice>}</section><aside className="inspector"><h2>Revision holati</h2><dl><dt>Manba</dt><dd>{revision?.source_type??'—'}</dd><dt>Revision</dt><dd>{revision?.revision_number??'—'}</dd><dt>Validatsiya</dt><dd><Status value={revision?.status}/></dd><dt>Natija</dt><dd><Status value={response.data.result_status}/></dd></dl><Notice title="O‘zgarmas provenance">Hisoblangan natija aynan shu revision va metodika versiyasiga bog‘lanadi.</Notice></aside></div></Page>
}
