import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useMemo, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Button, Empty, ErrorNotice, ErrorSummary, Field, Loading, Notice, Page, Pagination, Status } from '../components/UI'
import { useApi, useAuth } from '../context/AuthContext'
import { safeMessage } from '../lib/api'
import { can } from '../lib/capabilities'
import { tenantKey } from '../lib/queryKeys'
import type { InstrumentItem, Page as DataPage, Participant, ResponseDetail, ResponseItem, Version } from '../types'

const LIMIT=20
export function ResponsesPage(){
 const {researchId=''}=useParams();const call=useApi();const {membership}=useAuth();const [offset,setOffset]=useState(0);const key=tenantKey(membership?.organization_id,'responses',researchId,offset,LIMIT);const responses=useQuery({queryKey:key,queryFn:()=>call<DataPage<ResponseItem>>(`/api/v1/researches/${researchId}/responses?limit=${LIMIT}&offset=${offset}`)})
 return <section className="route-section"><header className="section-header"><div><p className="eyebrow">Immutable revisionlar</p><h2>Javoblar</h2></div>{can(membership?.role,'response:write')&&<Link className="button primary" to="new">Javob kiritish</Link>}</header>{responses.isLoading?<Loading/>:responses.error?<ErrorNotice error={responses.error}/>:!responses.data?.items.length?<Empty title="Javob hali yo‘q" icon="list-pen" action={can(membership?.role,'response:write')?<Link className="button primary" to="new">Manual kiritish</Link>:undefined}>Roziligi yaroqli ishtirokchini tanlab instrument javoblarini kiriting.</Empty>:<><div className="data-table-wrap"><table><thead><tr><th scope="col">Participant</th><th scope="col">Attempt</th><th scope="col">Revision</th><th scope="col">Holat</th><th scope="col">Yaratilgan</th><th scope="col">Amal</th></tr></thead><tbody>{responses.data.items.map(r=><tr key={r.id}><td data-label="Participant">{r.participant_external_code}</td><td data-label="Attempt">{r.attempt_key}</td><td data-label="Revision">{r.current_revision_number??'—'}</td><td data-label="Holat"><Status value={r.current_revision_status??r.status}/></td><td data-label="Yaratilgan">{new Date(r.created_at).toLocaleString('uz-Latn')}</td><td data-label="Amal"><Link to={`/responses/${r.id}`}>Ochish →</Link></td></tr>)}</tbody></table></div><Pagination offset={responses.data.offset} limit={responses.data.limit} total={responses.data.total} onChange={setOffset}/></>}</section>
}

export function ManualResponse(){
 const {researchId=''}=useParams();const call=useApi();const navigate=useNavigate();const {membership}=useAuth();const org=membership?.organization_id;const [participantId,setParticipantId]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const researches=useQuery({queryKey:tenantKey(org,'researches'),queryFn:()=>call<{id:string;methodology_version_id:string}[]>('/api/v1/researches')});const research=researches.data?.find(r=>r.id===researchId)
 const participants=useQuery({queryKey:tenantKey(org,'participants',researchId,'manual-picker'),queryFn:()=>call<DataPage<Participant>>(`/api/v1/researches/${researchId}/participants?limit=100`)});const version=useQuery({queryKey:tenantKey(org,'version',research?.methodology_version_id),enabled:Boolean(research),queryFn:()=>call<Version>(`/api/v1/methodology-versions/${research?.methodology_version_id}`)})
 const selected=participants.data?.items.find(p=>p.id===participantId);const items=version.data?.snapshot?.items??[];const promptsAllowed=Boolean(version.data?.licence?.allow_item_display&&items.length)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const answers:Record<string,unknown>={};for(const item of items){const raw=f.get(item.item_code);if(raw===null||raw==='')continue;answers[item.item_code]=canonical(item,raw)}setBusy(true);setError('');try{const response=await call<{id:string}>(`/api/v1/researches/${researchId}/responses`,{method:'POST',bodyJson:{participant_id:participantId,attempt_key:'initial',answers,finalize:true}});navigate(`/responses/${response.id}`)}catch(err){setError(safeMessage(err))}finally{setBusy(false)}}
 return <section className="route-section"><Link className="back-action" to="..">← Javoblar</Link><header><p className="eyebrow">Manual instrument</p><h2>Javoblarni kiriting</h2></header><form className="instrument" onSubmit={submit} aria-describedby={error?'manual-error':undefined}><ErrorSummary id="manual-error" error={error} title="Javob saqlanmadi"/><Field label="Ishtirokchi"><select value={participantId} onChange={e=>setParticipantId(e.target.value)} required><option value="">Pseudonimni tanlang</option>{participants.data?.items.map(p=><option key={p.id} value={p.id} disabled={!['granted','not_required_with_basis'].includes(p.current_consent_status??'')}>{p.external_code} · {p.current_consent_status??'consent yo‘q'}</option>)}</select></Field>{selected&&!['granted','not_required_with_basis'].includes(selected.current_consent_status??'')&&<Notice tone="warning" title="Processing bloklangan">Yaroqli consent bo‘lmasdan javob saqlanmaydi.</Notice>}{version.isLoading?<Loading label="Instrument olinmoqda"/>:!promptsAllowed?<Notice tone="warning" title="Savollarni ko‘rsatish cheklangan">Licence disclosure savol matnlarini ochishga ruxsat bermaydi. Prompt ixtiro qilinmaydi; ruxsat berilgan CSV oqimidan foydalaning.</Notice>:<ol className="instrument-list">{items.map((item,index)=><li key={item.item_code}><span className="item-number">{String(index+1).padStart(2,'0')}</span><div><p className="item-code">{item.item_code}{item.required?' · majburiy':''}</p><ItemInput item={item}/></div></li>)}</ol>}<div className="sticky-actions"><span>{items.length} savol · server canonical tekshiradi</span><Button type="submit" disabled={busy||!participantId||!promptsAllowed}>{busy?'Saqlanmoqda…':'Tekshirish va yakunlash'}</Button></div></form></section>
}
function ItemInput({item}:{item:InstrumentItem}){const label=item.prompt_i18n?.['uz-Latn']??item.prompt_i18n?.en??item.item_code;if(item.item_type==='boolean')return <fieldset><legend>{label}</legend><label className="choice"><input type="radio" name={item.item_code} value="true" required={item.required}/> Ha</label><label className="choice"><input type="radio" name={item.item_code} value="false"/> Yo‘q</label></fieldset>;if(item.item_type==='single_choice')return <fieldset><legend>{label}</legend>{item.options?.map(o=><label className="choice" key={o.option_code}><input type="radio" name={item.item_code} value={o.option_code} required={item.required}/>{o.label_i18n['uz-Latn']??o.option_code}</label>)}</fieldset>;return <Field label={label}><input name={item.item_code} type="number" step={item.item_type==='decimal'?'any':'1'} required={item.required}/></Field>}
function canonical(item:InstrumentItem,value:FormDataEntryValue){const text=String(value);if(item.item_type==='integer')return Number.parseInt(text,10);if(item.item_type==='decimal')return Number(text);if(item.item_type==='boolean')return text==='true';return text}

export function ResponseDetailPage(){
 const {responseId=''}=useParams();const call=useApi();const qc=useQueryClient();const navigate=useNavigate();const {membership}=useAuth();const org=membership?.organization_id;const [error,setError]=useState('');const [idempotency]=useState(()=>crypto.randomUUID())
 const key=tenantKey(org,'response',responseId);const response=useQuery({queryKey:key,queryFn:()=>call<ResponseDetail>(`/api/v1/responses/${responseId}`)});const revision=response.data?.current_revision;const summary=useMemo(()=>revision?.validation_summary?JSON.stringify(revision.validation_summary,null,2):'', [revision])
 async function validate(){setError('');try{await call(`/api/v1/responses/${responseId}/validate`,{method:'POST'});await qc.invalidateQueries({queryKey:key})}catch(err){setError(safeMessage(err))}}
 async function calculate(){if(!response.data?.current_revision_id)return;setError('');try{const result=await call<{id:string}>(`/api/v1/researches/${response.data.research_id}/calculations`,{method:'POST',bodyJson:{response_revision_id:response.data.current_revision_id,idempotency_key:idempotency}});navigate(`/results/${result.id}`)}catch(err){setError(safeMessage(err))}}
 if(response.isLoading)return <Loading/>;if(response.error)return <ErrorNotice error={response.error}/>;if(!response.data)return null
 return <Page eyebrow={`Participant ${response.data.participant_external_code}`} title={`Javob · revision ${revision?.revision_number??'—'}`} actions={<Status value={revision?.status??response.data.status}/>}><div className="provenance-strip"><span>Response <code>{responseId.slice(0,8)}…</code></span><span>Lock <strong>{response.data.lock_version}</strong></span><span>Hash <code>{revision?.answer_payload_hash.slice(0,12)??'—'}…</code></span></div><ErrorSummary error={error}/><div className="workbench-grid"><section><h2>Canonical validation</h2>{summary?<pre className="safe-json">{summary}</pre>:<p className="muted">Server validation xulosasi hali yo‘q.</p>}<div className="button-row">{revision?.status!=='validated'&&can(membership?.role,'response:write')&&<Button icon="list-checks" onClick={validate}>Serverda tekshirish</Button>}{revision?.status==='validated'&&can(membership?.role,'result:calculate')&&<Button icon="sigma" onClick={calculate}>Natijani hisoblash</Button>}</div>{revision?.status!=='validated'&&!can(membership?.role,'response:write')&&<Notice title="Faqat o‘qish">Sizning rolingiz revisionni tekshira olmaydi.</Notice>}</section><aside className="inspector"><h2>Revision holati</h2><dl><dt>Manba</dt><dd>{revision?.source_type??'—'}</dd><dt>Revision</dt><dd>{revision?.revision_number??'—'}</dd><dt>Validatsiya</dt><dd><Status value={revision?.status}/></dd><dt>Idempotency ref</dt><dd><code>{idempotency.slice(0,12)}…</code></dd></dl><Notice title="O‘zgarmas provenance">Hisoblangan natija aynan shu revision va metodika versiyasiga bog‘lanadi.</Notice></aside></div></Page>
}
